version: '3'

networks:
  bridge:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      -  'MONGODB_USER=user' 
      -  'MONGODB_PASS=password!'
    volumes:
      - 'mongodb-data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles  
  app:
    build:
      context: .      # Dockerfile保存場所
      dockerfile: Dockerfile    # Dockerfileファイル名
    image: rc-map_front                  # イメージ名
    container_name: app         # コンテナ名
    ports:                          # ポート接続
      - 3000:3000
    volumes:                        # mount workdir
      - ./app:/src
    command: [sh, -c, npm i && npm start]
  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: rc-map_api
    container_name: db
    ports:
     - '27017:27017'
     - '8081:8081'
    volumes:
     - 'mongodb-data:/data/db'
    environment:
     - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
     - 'ME_CONFIG_BASICAUTH_USERNAME=user'
     - 'ME_CONFIG_BASICAUTH_PASSWORD=password!'
    command: mongod --smallfiles
volumes:
  mongodb-data: {}